#!/bin/zsh

source "$HOME/.config/omarchy-mac/current.sh"

options=(
  style=round
  width=5.0
  hidpi=on
  active_color="$BORDER_ACTIVE"
  inactive_color="$BORDER_INACTIVE"
)

exec /opt/homebrew/bin/borders "${options[@]}"
